# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sample_pb2 as sample__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x1a\x0csample.proto\"W\n\x05InOut\x12\x17\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.ErrorH\x00\x12\x11\n\x07integer\x18\x02 \x01(\rH\x00\x12\x19\n\x06record\x18\x03 \x01(\x0b\x32\x07.RecordH\x00\x42\x07\n\x05value\"8\n\x07Request\x12\x17\n\x04\x66unc\x18\x01 \x01(\x0e\x32\t.FUNCTION\x12\x14\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x06.InOut\"\x08\n\x06\x43\x61ncel\"?\n\x08Response\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.ResponseType\x12\x16\n\x06result\x18\x02 \x01(\x0b\x32\x06.InOut\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xca\x01\n\x07Message\x12\x0f\n\x07version\x18\x01 \x02(\r\x12\x0c\n\x04m_id\x18\x02 \x01(\r\x12\x0e\n\x06rpc_id\x18\x03 \x01(\r\x12\x0e\n\x06source\x18\x04 \x01(\r\x12\x0e\n\x06target\x18\x05 \x01(\r\x12\x1b\n\x07request\x18\x06 \x01(\x0b\x32\x08.RequestH\x00\x12\x19\n\x06\x63\x61ncel\x18\x07 \x01(\x0b\x32\x07.CancelH\x00\x12\x1d\n\x08response\x18\x08 \x01(\x0b\x32\t.ResponseH\x00\x12\x11\n\x08\x63hecksum\x18\xe7\x07 \x02(\rB\x06\n\x04\x64\x61ta*S\n\x08\x46UNCTION\x12\r\n\tFUNC_NONE\x10\x00\x12\r\n\tFUNC_PING\x10\x01\x12\x13\n\x0f\x46UNC_GET_RECORD\x10\x02\x12\x14\n\x10\x46UNC_POST_RECORD\x10\x03*&\n\x0cResponseType\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNCTION']._serialized_start=494
  _globals['_FUNCTION']._serialized_end=577
  _globals['_RESPONSETYPE']._serialized_start=579
  _globals['_RESPONSETYPE']._serialized_end=617
  _globals['_INOUT']._serialized_start=27
  _globals['_INOUT']._serialized_end=114
  _globals['_REQUEST']._serialized_start=116
  _globals['_REQUEST']._serialized_end=172
  _globals['_CANCEL']._serialized_start=174
  _globals['_CANCEL']._serialized_end=182
  _globals['_RESPONSE']._serialized_start=184
  _globals['_RESPONSE']._serialized_end=247
  _globals['_ERROR']._serialized_start=249
  _globals['_ERROR']._serialized_end=287
  _globals['_MESSAGE']._serialized_start=290
  _globals['_MESSAGE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
