# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\"5\n\x08Location\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.LocationType\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0bValue_Float\x12\r\n\x05value\x18\x01 \x01(\x02\"f\n\x06Sample\x12\x19\n\x07species\x18\x01 \x01(\x0e\x32\x08.Species\x12\x15\n\x05units\x18\x02 \x01(\x0e\x32\x06.Units\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x1b\n\x08location\x18\x05 \x03(\x0b\x32\t.Location\"8\n\x06Record\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x04\x12\x18\n\x07samples\x18\x03 \x03(\x0b\x32\x07.Sample*\x9b\x03\n\x07Species\x12\x12\n\x0eSPECIE_UNKNOWN\x10\x00\x12\x18\n\x14SPECIE_SAMPLE_NUMBER\x10\x01\x12\x16\n\x12SPECIE_TEMPERATURE\x10\x02\x12\x13\n\x0fSPECIE_HUMIDITY\x10\x03\x12\x13\n\x0fSPECIE_PRESSURE\x10\x04\x12\x1b\n\x17SPECIE_O2_CONCENTRATION\x10\x05\x12\x1b\n\x17SPECIE_H2_CONCENTRATION\x10\x06\x12 \n\x1cSPECIE_METHANE_CONCENTRATION\x10\x07\x12\x1c\n\x18SPECIE_CO2_CONCENTRATION\x10\x08\x12\x17\n\x13SPECIE_ACCELERATION\x10\t\x12\x14\n\x10SPECIE_GYROSCOPE\x10\n\x12\x12\n\x0eSPECIE_COMPASS\x10\x0b\x12\x12\n\x0eSPECIE_VOLTAGE\x10\x0c\x12\x12\n\x0eSPECIE_CURRENT\x10\r\x12\x10\n\x0cSPECIE_POWER\x10\x0e\x12\x13\n\x0fSPECIE_LATITUDE\x10\x0f\x12\x14\n\x10SPECIE_LONGITUDE\x10\x10*\x8a\x02\n\x05Units\x12\x10\n\x0cUNIT_UNKNOWN\x10\x00\x12\x11\n\rUNIT_UNITLESS\x10\x01\x12\x13\n\x0fUNIT_FAHRENHEIT\x10\x02\x12\x10\n\x0cUNIT_CELSIUS\x10\x03\x12\x0c\n\x08UNIT_PPB\x10\x04\x12\x0c\n\x08UNIT_PPM\x10\x05\x12\x10\n\x0cUNIT_PERCENT\x10\x06\x12\r\n\tUNIT_MBAR\x10\x07\x12\x0f\n\x0bUNIT_PASCAL\x10\x08\x12\x10\n\x0cUNIT_MILLI_G\x10\t\x12\x14\n\x10UNIT_DEG_PER_SEC\x10\n\x12\x10\n\x0cUNIT_MILLI_T\x10\x0b\x12\x0e\n\nUNIT_VOLTS\x10\x0c\x12\r\n\tUNIT_AMPS\x10\r\x12\x0e\n\nUNIT_WATTS\x10\x0e*y\n\x0cLocationType\x12\x14\n\x10LOCATION_UNKNOWN\x10\x00\x12\x15\n\x11LOCATION_BACKPACK\x10\x01\x12\x11\n\rLOCATION_MAIN\x10\x02\x12\x17\n\x13LOCATION_FLOW_METER\x10\x03\x12\x10\n\x0cLOCATION_PAM\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPECIES']._serialized_start=264
  _globals['_SPECIES']._serialized_end=675
  _globals['_UNITS']._serialized_start=678
  _globals['_UNITS']._serialized_end=944
  _globals['_LOCATIONTYPE']._serialized_start=946
  _globals['_LOCATIONTYPE']._serialized_end=1067
  _globals['_LOCATION']._serialized_start=16
  _globals['_LOCATION']._serialized_end=69
  _globals['_VALUE_FLOAT']._serialized_start=71
  _globals['_VALUE_FLOAT']._serialized_end=99
  _globals['_SAMPLE']._serialized_start=101
  _globals['_SAMPLE']._serialized_end=203
  _globals['_RECORD']._serialized_start=205
  _globals['_RECORD']._serialized_end=261
# @@protoc_insertion_point(module_scope)
